### ISSUE TITLE
ERROR: Failed to parse RIS Live raw data 

### ISSUE THREAD

**Issue by tomgreenwood1** [CAIDA/pybgpstream#29] opened 2020-04-29 17:35 UTC
I am getting this error: `ERROR: Failed to parse RIS Live raw data`

I'm running my code inside a container build on `caida/bgpstream:2.0.0-rc3`

The error message is also accompanied by `WARNING: Corrupted RIS Live message:`

Any idea what could be causing this? Weirdly, I don't get this error if I run the code on my desktop, which has a slightly older version of bgpstream on it..

The pybgpstream code I'm using is:
```python
stream = pybgpstream.BGPStream(
     from_time=start_time,
     collector="route-views.linx",
     record_type="updates" )
```
If I run that locally, nothing happens, but there are no error messages.

whereas if I use:
```python
TEST_FILE_PATH = "/home/tomg/Downloads/updates.20200416.0430"
stream = pybgpstream.BGPStream()
stream.set_data_interface("singlefile")
stream.set_data_interface_option("singlefile", "upd-file", TEST_FILE_PATH)
stream.start
```
Locally, it works fine. In the container (I copied the file in), nothing happens (but no error messages either)

**Comment by alistairking** [comment] 2020-04-29 18:35
Hi!

Thanks for reaching out.

I think this is caused by the combination of a "feature", and a bug.

The "feature" is that when you only provide a start time, BGPStream goes into "live" mode which means it will include data from RIS Live. Because we don't have a mechanism for checking which collectors a given live stream (e.g., RIS Live) contains, we are uselessly opening this stream (i.e., the system doesn't know that the RIS Live stream doesn't include data from the route-views.linx collector).

Then, you are hitting a bug with how BGPStream handles the RIS Live stream which causes things to break. (This issue is why v2 is still in a pre-release state.)

I _think_ that if you set
```python
project="routeviews",
```
in the constructor you should see more sane behavior.

**Comment by tomgreenwood1** [comment] 2020-04-29 18:48
Thanks very much for the prompt response! 

Just to clarify: should I include `project=routeviews` AND `collector=route-views.linx` or should I just put `project=routeviews` and then filter it down to the collector I want in my code? I have to have it both live and for just a single collector or I'm screwed. 

Alternatively, could I roll back to and earlier version?

Thanks again

**Comment by alistairking** [comment] 2020-04-29 18:54
Yeah, include them both.

**Comment by tomgreenwood1** [comment] 2020-05-01 07:05
Thanks Alistair,

This code seems to work just fine for me:
```python
stream = pybgpstream.BGPStream(
    from_time=start_time,
    project="routeviews",
    collector="route-views.linx",
    record_type="updates"
)
```

Shall I close the issue, since my problem is solved for now, or leave it open, since there's an underlying bug in there?

**Comment by alistairking** [comment] 2020-05-01 14:59
I think we can go ahead and close it. We're tracking the underlying bug over at https://github.com/CAIDA/libbgpstream/issues/116

**Closed by alistairking** 2020-05-01 14:59 UTC
